### ISSUE TITLE
怎么提示缺少一个config.json文件

### ISSUE THREAD

**Issue by kingsmile07** [selfmakeit/wechatBot#2]
read cinfig file error
panic: open config/config.json: The system cannot find the file specified.

goroutine 1 [running]:
wechatbot/config.loadConfig()
        G:/下载目录/Compressed/wechatBot-master/config/config.go:77 +0x1d6
wechatbot/config.init.0()
        G:/下载目录/Compressed/wechatBot-master/config/config.go:65 +0xf

**Comment by tuzi95555** [comment]
> read cinfig file error panic: open config/config.json: The system cannot find the file specified.
> 
> goroutine 1 [running]: wechatbot/config.loadConfig() G:/下载目录/Compressed/wechatBot-master/config/config.go:77 +0x1d6 wechatbot/config.init.0() G:/下载目录/Compressed/wechatBot-master/config/config.go:65 +0xf

一样的，老哥有这个json文件不？
